#ifndef _bus_comm_H_
#define _bus_comm_H_
#include "can_controller.h"
#define CAN_GROUP 0x101u

/*
 * @brief Process a frame generated by the bus and sends to pc / executes
 * @returns
 */
bool process_can_frame(CanFrame_t frame);

void bus_recover(void);

#endif