#ifndef _CAN_COMM_H_
#define _CAN_COMM_H_
#include "can_controller.h"

/*
 * @brief Process a frame generated by the bus and sends to pc / executes
 * @returns
 */
bool process_can_frame(CanFrame_t frame);

#endif